#!/bin/bash

PATH="${PWD}/.api_token"

# generate api token if non exists
if [ ! -f "$PATH" ];then
  echo $(tr -dc A-Za-z0-9 </dev/urandom | head -c 13 ; echo '') > .api_token
else
  echo "Could not generate api token"
  echo "API token already exists"
  echo $PATH
fi